import {chromium} from '/Users/alialmashjari/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';
const base='http://127.0.0.1:4180';const out='/private/tmp/f6een-final-audit';fs.mkdirSync(out+'/screenshots',{recursive:true});
const browser=await chromium.launch({headless:true});const results=[];
const uid='00000000-0000-0000-0000-000000000001';
const user={id:uid,aud:'authenticated',role:'authenticated',email:'audit@example.invalid',user_metadata:{full_name:'Audit User'},app_metadata:{provider:'email'},created_at:new Date().toISOString()};
const token=()=>[Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'),Buffer.from(JSON.stringify({sub:uid,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),'audit'].join('.');
async function fixture(page,phase='stage1-board',opts={}){return page.evaluate(async({phase,opts})=>{const se=await import('/src/game/session.ts');const b=await import('/src/game/bank.ts');const r=await import('/src/game/reducer.ts');let s=se.createSession({teamNames:['فريق الشمس','فريق القمر'],players:[Array.from({length:opts.players??2},(_,i)=>'لاعب الشمس '+(i+1)),Array.from({length:opts.players??2},(_,i)=>'لاعب القمر '+(i+1))],startingTeam:0,categories:b.playableCategories().slice(0,6)});s=r.reducer(s,{t:'S1_PICK',category:s.s1Categories[0].name,level:'سهل'});const q=opts.photo?b.ALL_QUESTIONS.find(q=>q.image):opts.long?b.ALL_QUESTIONS.filter(q=>!q.image).sort((a,b)=>b.question.length-a.question.length)[0]:s.currentQuestion;s={...s,phase,currentQuestion:q,s2Sel:[0,0],s3Queue:[q,...s.s3Queue],s3Team:opts.second?1:0,s3Done:opts.second?[0]:[],s3Revealed:!!opts.revealed};if(phase==='stage1-board'){s.currentQuestion=null;s.s1Cell=null;s.s1Played=[];s.s1Index=0;s.askedQuestionIds=[]}if(phase==='endgame'){s.teams[0].score=100;s.stagePoints.s1=[100,0];s.s3Counts.correct=[12,12]}return se.encodeState(s)},{phase,opts})}
async function create({auth=true,state=null,viewport={width:1440,height:900},mock={},touch=false}={}){
const context=await browser.newContext({viewport,hasTouch:touch,isMobile:touch});const page=await context.newPage();const events={errors:[],calls:[]};page.on('pageerror',e=>events.errors.push(e.message));
await page.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(url.origin!==base)return route.abort();if(!url.pathname.startsWith('/test-backend'))return route.continue();const p=url.pathname.split('/').pop();const body=req.postDataJSON?.();events.calls.push({p,method:req.method(),body});if(mock[p]){const answer=await mock[p](req,events);if(answer)return route.fulfill({contentType:'application/json',...answer})}
let data=[];if(p==='user')data=user;else if(p==='profiles')data={games_balance:5,created_at:new Date().toISOString()};else if(p==='start_session')data={id:'11111111-1111-1111-1111-111111111111',state:body.initial_state};else if(p==='bank_signature')data=null;else if(p==='question_bank')data={mode:'overlay',rows:[]};else if(p==='is_admin'||p==='is_super')data=false;else if(p==='bank_mode')data=false;return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)});});
await page.goto(base+'/audit-blank.html');if(auth)await page.evaluate(({user,t})=>localStorage.setItem('sb-127-auth-token',JSON.stringify({access_token:t,refresh_token:'test-refresh',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,token_type:'bearer',user})),{user,t:token()});
if(state)await save(page,state);return {page,context,events};}
async function save(page,state){await page.evaluate(s=>{localStorage.setItem('f6een.session',JSON.stringify({version:6,savedAt:Date.now(),sessionId:'11111111-1111-1111-1111-111111111111',state:s}));localStorage.setItem('f6een.muted','1')},state)}
async function run(name,fn){let r;try{r=await fn();results.push({name,...r})}catch(e){results.push({name,status:'HARNESS_ERROR',error:e.message})}fs.writeFileSync(out+'/browser-results.json',JSON.stringify(results,null,2));console.log(name,JSON.stringify(results.at(-1)))}
await run('signed-out entry renders Arabic login without crash',async()=>{const x=await create({auth:false});await x.page.goto(base);await x.page.getByRole('button',{name:'المتابعة بالبريد'}).waitFor();const r={status:x.events.errors.length?'FAIL':'PASS',errors:x.events.errors};await x.context.close();return r});
await run('empty signup shows Arabic validation',async()=>{const x=await create({auth:false});await x.page.goto(base);await x.page.getByRole('button',{name:'المتابعة بالبريد'}).click();await x.page.getByRole('button',{name:'إنشاء الحساب',exact:true}).click();const r={status:await x.page.getByText('اكتب اسمك الأول',{exact:true}).isVisible()?'PASS':'FAIL'};await x.context.close();return r});
await run('sprint reload preserves elapsed time',async()=>{const x=await create();await save(x.page,await fixture(x.page,'stage3-play'));await x.page.goto(base);await x.page.getByRole('button',{name:'ابدأ الآن'}).click();await x.page.waitForTimeout(1200);await x.page.getByRole('button',{name:'اكشف الإجابة',exact:true}).click();await x.page.locator('.v.correct').click();const before=await x.page.locator('.secs').innerText();await x.page.reload();await x.page.getByRole('button',{name:'ابدأ الآن'}).waitFor();await x.page.getByRole('button',{name:'ابدأ الآن'}).click();const after=await x.page.locator('.secs').innerText();const snap=JSON.parse(await x.page.evaluate(()=>localStorage.getItem('f6een.session')));await x.page.screenshot({path:out+'/screenshots/sprint-reload.png'});const r={status:Number(after)<=Number(before)?'PASS':'FAIL',before,after,retainedScore:snap.state.teams[0].score};await x.context.close();return r});
await run('malformed restored question produces recoverable UI',async()=>{const x=await create();const s=await fixture(x.page,'stage2-question');s.currentQuestion=null;s.s2Sel=null;await save(x.page,s);await x.page.goto(base);await x.page.waitForTimeout(600);const r={status:x.events.errors.length?'FAIL':'PASS',errors:x.events.errors,bodyText:await x.page.locator('#root').innerText()};await x.context.close();return r});
await run('offline report truthfully reflects pending delivery',async()=>{const x=await create({mock:{report_question:async()=>({status:503,body:'{"message":"offline"}'})}});const s=await fixture(x.page,'endgame');s.phase='tiebreak';s.s3Revealed=true;await save(x.page,s);await x.page.goto(base);await x.page.getByRole('button',{name:'أصاب فريق الشمس',exact:true}).click();await x.page.getByRole('button',{name:'بلّغ عن سؤال',exact:true}).click();await x.page.getByRole('button',{name:'بلّغ',exact:true}).first().click();await x.page.waitForTimeout(300);const label=await x.page.locator('.rp-btn').first().innerText();const block=await x.page.evaluate(()=>localStorage.getItem('f6een.blockedQuestionIds'));const r={status:label==='بُلّغ'&&block==='[]'?'FAIL':'PASS',label,localBlocked:block};await x.context.close();return r});
await run('image removal does not implicitly submit question form',async()=>{let saves=0;const q={question_id:'AUDIT',category:'جغرافيا ومعالم',level:'سهل',topic:null,question:'من صاحب الصورة؟',answer:'اختبار',image:'https://example.invalid/photo.jpg',family:null,origin:'new',updated_at:new Date().toISOString()};const x=await create({mock:{is_admin:async()=>({body:'true'}),is_super:async()=>({body:'true'}),admin_questions:async()=>({body:JSON.stringify([q])}),admin_stats:async()=>({body:'{}'}),admin_save_question:async()=>{saves++;return {body:'"AUDIT"'}}}});await x.page.goto(base+'/admin.html');await x.page.getByRole('combobox').nth(2).selectOption('added');await x.page.getByRole('button',{name:'تعديل',exact:true}).first().click();await x.page.getByRole('button',{name:'إزالة',exact:true}).click();await x.page.waitForTimeout(300);const r={status:saves===0?'PASS':'FAIL',saveRequests:saves};await x.context.close();return r});
await run('completed game stays completed after failed close and reload',async()=>{let serverState;const x=await create({mock:{sessions:async req=>req.method()==='PATCH'?{status:503,body:'{"message":"offline"}'}:{body:JSON.stringify([{id:'11111111-1111-1111-1111-111111111111',state:serverState}])}}});serverState=await fixture(x.page,'stage3-play',{second:true});const end=await fixture(x.page,'endgame');end.phase='tiebreak';end.s3Revealed=true;await save(x.page,end);await x.page.goto(base);await x.page.getByRole('button',{name:'أصاب فريق الشمس',exact:true}).click();await x.page.getByRole('button',{name:'لعبة جديدة',exact:true}).waitFor();await x.page.waitForTimeout(100);await x.page.reload();await x.page.waitForTimeout(500);const resumed=await x.page.getByRole('button',{name:'ابدأ الآن',exact:true}).isVisible();const r={status:resumed?'FAIL':'PASS',resumedOldRound:resumed};await x.context.close();return r});
await run('layout matrix: required controls remain in viewport',async()=>{const checks=[];for(const viewport of [{width:1920,height:1080},{width:1024,height:768},{width:844,height:390}]){const x=await create({viewport});for(const [phase,opts] of [['stage1-board',{}],['stage1-question',{long:true}],['stage1-question',{photo:true}],['stage1-reveal',{long:true}],['stage2-question',{photo:true}],['stage2-reveal',{long:true}],['stage3-play',{photo:true}],['tiebreak',{long:true,revealed:true}],['endgame',{players:6}]]){const f=await fixture(x.page,phase,opts);if(phase==='endgame'){f.phase='tiebreak';f.s3Revealed=true}await save(x.page,f);await x.page.goto(base);if(phase==='endgame')await x.page.getByRole('button',{name:'أصاب فريق الشمس',exact:true}).click();await x.page.waitForTimeout(650);if(phase==='stage3-play'){await x.page.getByRole('button',{name:'ابدأ الآن'}).click();await x.page.getByRole('button',{name:'اكشف الإجابة',exact:true}).click()}await x.page.evaluate(()=>document.fonts.ready);const issues=await x.page.evaluate(()=>[...document.querySelectorAll('#root button')].filter(e=>e.getClientRects().length&&!e.disabled).map(e=>({text:e.textContent.trim(),r:e.getBoundingClientRect()})).filter(({r})=>r.x< -1||r.y< -1||r.right>innerWidth+1||r.bottom>innerHeight+1).map(({text,r})=>({text,x:r.x,y:r.y,w:r.width,h:r.height})));checks.push({size:viewport.width+'x'+viewport.height,phase,variant:opts,issues});if(issues.length||viewport.width===844&&phase==='endgame')await x.page.screenshot({path:out+'/screenshots/'+viewport.width+'-'+phase+(opts.photo?'-photo':'')+'.png'})}await x.context.close()}return {status:checks.some(x=>x.issues.length)?'FAIL':'PASS',checks}});
await run('complete browser game: setup, board, derby, both sprint turns, final result',async()=>{
 const x=await create();await x.page.goto(base+'/?fast');
 await x.page.locator('.team-name').nth(0).fill('الشمس');await x.page.locator('.team-name').nth(1).fill('القمر');
 for(let i=0;i<4;i++)await x.page.locator('input.player').nth(i).fill('لاعب '+i);
 for(let i=0;i<6;i++)await x.page.locator('.catchip').nth(i).click();
 await x.page.getByRole('button',{name:'قرعة البدء',exact:true}).click();await x.page.getByRole('button',{name:'إعادة القرعة',exact:true}).waitFor();
 await x.page.getByRole('button',{name:'ابدأ اللعبة',exact:true}).click();const seen=[];
 for(let i=0;i<18;i++){await x.page.locator('.bcell:not([disabled])').first().click();seen.push(JSON.parse(await x.page.evaluate(()=>localStorage.getItem('f6een.session'))).state.currentQuestion.id);await x.page.getByRole('button',{name:'اكشف الإجابة',exact:true}).click();await x.page.locator('.pick-team').first().click()}
 await x.page.getByRole('button',{name:'ابدأ',exact:true}).click();
 for(let i=0;i<4;i++){await x.page.locator('.s2-question-body').waitFor({timeout:15000});seen.push(JSON.parse(await x.page.evaluate(()=>localStorage.getItem('f6een.session'))).state.currentQuestion.id);await x.page.getByRole('button',{name:'كشف الإجابة',exact:true}).click();await x.page.locator('.mcard').first().locator('.choice.ok').click();await x.page.getByRole('button',{name:'الجولة التالية',exact:true}).click()}
 await x.page.getByRole('button',{name:'ابدأ',exact:true}).click();
 for(let t=0;t<2;t++){await x.page.getByRole('button',{name:'ابدأ الآن',exact:true}).click();await x.page.getByRole('button',{name:'اكشف الإجابة',exact:true}).click();await x.page.locator('.v.correct').click();await x.page.waitForTimeout(3200)}
 await x.page.getByRole('button',{name:'لعبة جديدة',exact:true}).waitFor();const s=JSON.parse(await x.page.evaluate(()=>localStorage.getItem('f6een.session'))).state;
 const r={status:s.phase==='endgame'&&new Set(seen).size===seen.length&&s.teams[0].score===450&&s.teams[1].score===10&&x.events.errors.length===0?'PASS':'FAIL',scores:s.teams.map(t=>t.score),phase:s.phase,boardAndDerbyQuestions:seen.length,errors:x.events.errors};
 await x.page.screenshot({path:out+'/screenshots/full-session-end.png'});await x.context.close();return r;
});

await browser.close();
