import {PGlite} from '/private/tmp/f6een-audit-db/node_modules/@electric-sql/pglite/dist/index.js';
import fs from 'node:fs';
const db=new PGlite();const results=[];const U='00000000-0000-0000-0000-000000000001',B='00000000-0000-0000-0000-000000000002',E='00000000-0000-0000-0000-000000000003',S='00000000-0000-0000-0000-000000000004';
const test=async(name,fn)=>{try{const r=await fn();results.push({name,...r});console.log(name,JSON.stringify(r))}catch(e){results.push({name,status:'HARNESS_ERROR',error:e.message});console.log(name,e.message)}};
await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}',created_at timestamptz default now());create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;create table storage.buckets(id text primary key,name text,public boolean);create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);grant usage on schema public,auth,storage to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;alter default privileges in schema public grant select,insert,update,delete on tables to authenticated;`);
const migrations=fs.readdirSync('supabase/migrations').sort();
for(const f of migrations){try{await db.exec(fs.readFileSync('supabase/migrations/'+f,'utf8'))}catch(e){console.log('MIGRATION FAILED',f,e.message);throw e}}
results.push({name:'all migrations apply on clean PostgreSQL-compatible database',status:'PASS',count:migrations.length});
await db.exec(`insert into auth.users(id,email) values ('${U}','u@test.invalid'),('${B}','b@test.invalid'),('${E}','editor@test.invalid'),('${S}','super@test.invalid');insert into public.admins(id,role) values ('${E}','editor'),('${S}','super');`);
async function user(uid,fn){await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${uid}',false);`);try{return await fn()}finally{await db.exec('reset role')}}
const one=async(q,p=[]) => (await db.query(q,p)).rows[0];
await test('new accounts get one free game',async()=>({status:(await one('select games_balance from profiles where id=$1',[U])).games_balance===1?'PASS':'FAIL'}));
let sid;
await test('starting a session charges once; resume does not charge again',async()=>user(U,async()=>{sid=(await one(`select (public.start_session('{}')).id`)).id;const second=(await one(`select (public.start_session('{}')).id`)).id;const b=await one('select games_balance from profiles');return {status:sid===second&&b.games_balance===0?'PASS':'FAIL'}}));
await test('another account cannot update or read the first session',async()=>user(B,async()=>{const r=await db.query('update sessions set state=$1 where id=$2 returning id',[{tampered:true},sid]);const reads=await db.query('select id from sessions where id=$1',[sid]);return {status:r.rows.length===0&&reads.rows.length===0?'PASS':'FAIL'}}));
await test('ordinary player cannot directly change balance',async()=>user(U,async()=>{const r=await db.query('update profiles set games_balance=999 where id=$1 returning id',[U]);return {status:r.rows.length===0?'PASS':'FAIL'}}));
await test('finished sessions cannot be reopened by their owner',async()=>user(U,async()=>{await db.query("update sessions set status='finished' where id=$1",[sid]);const r=await db.query("update sessions set status='open',state='{}' where id=$1 returning id",[sid]);const resumed=await one(`select (public.start_session('{}')).id`);return {status:r.rows.length===0?'PASS':'FAIL',reopened:r.rows.length===1,reusedWithoutBalance:resumed.id===sid}}));
await test('editor cannot change balances',async()=>user(E,async()=>{try{await db.query('select admin_set_balance($1,99)',[U]);return {status:'FAIL'}}catch(e){return {status:e.message.includes('not_super')?'PASS':'FAIL'}}}));
await test('super admin can change balances',async()=>user(S,async()=>{await db.query('select admin_set_balance($1,3)',[U]);return {status:(await one('select games_balance from profiles where id=$1',[U])).games_balance===3?'PASS':'FAIL'}}));
await test('gift redemption is limited to once per user',async()=>{await user(S,()=>db.query("select admin_create_gift_code('AUDIT',1,10,null,'tester')"));return user(U,async()=>{await db.query("select redeem_gift_code('AUDIT')");try{await db.query("select redeem_gift_code('AUDIT')");return {status:'FAIL'}}catch(e){return {status:e.message==='code_already_used'?'PASS':'FAIL'}}})});
await test('gift codes accept lowercase input like their uppercase canonical form',async()=>user(B,async()=>{try{await db.query("select redeem_gift_code('audit')");return {status:'PASS'}}catch(e){return {status:'FAIL',error:e.message}}}));
await db.exec(`insert into question_overrides(question_id,category,level,question,answer,origin) select 'Q'||n,'C','سهل','q'||n,'a','bank' from generate_series(1,20)n;insert into app_flags(key,enabled)values('bank_in_db',true);`);
await test('delete floor blocks reduction from twenty to nineteen',async()=>user(E,async()=>{try{await db.query("select admin_delete_question('Q1')");return {status:'FAIL'}}catch(e){return {status:e.message.includes('cell_floor')?'PASS':'FAIL'}}}));
await test('moving a question respects the same twenty-question floor',async()=>user(E,async()=>{await db.query("select admin_save_question('Q1','Other','سهل',null,'q1','a',null)");const r=await one("select count(*)::int as n from question_overrides where category='C'");return {status:r.n>=20?'PASS':'FAIL',remaining:r.n}}));
await test('ordinary users cannot call admin question functions',async()=>user(U,async()=>{try{await db.query("select admin_save_question(null,'C','سهل',null,'hacked','a',null)");return {status:'FAIL'}}catch(e){return {status:e.message==='not_admin'?'PASS':'FAIL'}}}));
await test('only super admins read contact messages',async()=>{await user(U,()=>db.query("select send_message('hello',null)"));return user(E,async()=>({status:(await db.query('select * from messages')).rows.length===0&&(await db.query('select * from admin_messages()')).rows.length===0?'PASS':'FAIL'}))});
await test('reporting only accepts questions actually shown in a completed session',async()=>user(U,async()=>{await db.query("select report_question('not-a-real-question',null)");const r=await db.query("select * from blocked_questions() where question_id='not-a-real-question'");return {status:r.rows.length===0?'PASS':'FAIL',blockedArbitraryId:r.rows.length===1}}));
await test('bank mode cannot activate with an incomplete seed when expectation omitted',async()=>user(E,async()=>{await db.query('select admin_set_bank_mode(false)');await db.query('select admin_set_bank_mode(true)');return {status:'FAIL',activatedWithOnly20Rows:true}}));
fs.writeFileSync('db-results.json',JSON.stringify({engine:'PGlite embedded PostgreSQL; Supabase auth/storage schemas and default grants modeled locally',results},null,2));await db.close();
