/* نظام تصميم صحصحلي — لعبة أسئلة عربية تُلعب على شاشة واحدة كبيرة في المجلس.
   كل مكوّن هنا مأخوذ من التطبيق نفسه لا مؤلَّف من جديد. */
export { Screen } from './Screen'
export type { ScreenProps } from './Screen'
export { Button } from './Button'
export type { ButtonProps } from './Button'
export { ActionNote } from './ActionNote'
export type { ActionNoteProps } from './ActionNote'
export { Eyebrow } from './Eyebrow'
export type { EyebrowProps } from './Eyebrow'
export { ScoreBar } from './ScoreBar'
export type { ScoreBarProps, ScoreBarTeam } from './ScoreBar'
export { Timer } from './Timer'
export type { TimerProps } from './Timer'
export { QuestionCard } from './QuestionCard'
export type { QuestionCardProps } from './QuestionCard'
export { AnswerReveal } from './AnswerReveal'
export type { AnswerRevealProps } from './AnswerReveal'
export { HexCell } from './HexCell'
export type { HexCellProps } from './HexCell'
export { HexGrid } from './HexGrid'
export type { HexGridProps } from './HexGrid'
export { Chip } from './Chip'
export type { ChipProps } from './Chip'
export { StatRow } from './StatRow'
export type { StatRowProps } from './StatRow'
export { ChoiceBox } from './ChoiceBox'
export type { ChoiceBoxProps } from './ChoiceBox'
export { PlayerCard } from './PlayerCard'
export type { PlayerCardProps } from './PlayerCard'
export { VersusPair } from './VersusPair'
export type { VersusPairProps } from './VersusPair'
export { IntervalCard } from './IntervalCard'
export type { IntervalCardProps } from './IntervalCard'
export { TeamSetupCard } from './TeamSetupCard'
export type { TeamSetupCardProps } from './TeamSetupCard'
export { BrandMark } from './BrandMark'
export type { BrandMarkProps } from './BrandMark'
